language: rust
cache: cargo

rust:
  - nightly
# - stable

# Dependencies of ptx-linker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - llvm-6.0-dev

env:
  - LLVM_SYS_60_PREFIX="/usr/lib/llvm-6.0"

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install -f xargo
  - cargo install -f ptx-linker
  - rustup component add rust-src

script:
  - cargo check
  - cargo test

branches:
  only:
  - master

notifications:
  email:
    on_success: never