language: rust
cache: cargo
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "Check with Clippy"
      install:
        - rustup component add clippy
      script:
        - cargo clippy -- --verbose

    - name: "Check with Rustfmt"
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

    - name: "Run tests"
      install:
        - cargo install -f ptx-linker
        - rustup target add nvptx64-nvidia-cuda
      script:
        - cargo test --verbose

notifications:
  email:
    on_success: never

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
