language: rust
cache: cargo

rust:
  - nightly

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install -f xargo
  - cargo install -f ptx-linker
  - rustup component add rust-src

script:
  - cargo check
  - cargo test

branches:
  only:
  - master

notifications:
  email:
    on_success: never
