[package]
name = "ptx-builder"
version = "0.3.2"
description = "NVPTX build helper"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
repository = "https://github.com/denzp/rust-ptx-builder"
readme = "README.md"
license = "MIT"

exclude = [
    "tests/**/*",
]

[dependencies]
error-chain = "0.11"
colored = "1.6"
toml = "0.4"
semver = "0.9"
regex = "0.2"

[dev-dependencies]
lazy_static = "1.0"

[badges]
travis-ci = { repository = "denzp/rust-ptx-builder", branch = "master" }